apiVersion: v1
kind: Secret
metadata:
  name: transaction-service-secrets
  namespace: one-gate-payment
  labels:
    app: transaction-service
type: Opaque
stringData:
  db-username: "developer"
  db-password: "developer123"
  redis-password: "developer123"